### ISSUE TITLE
Scrub images by default

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-replay#232]
**Problem:**

Today, our default privacy configuration masks texts and inputs on replay videos. However, images still are present, potentially leaking sensitive information.

**Solution:**

- [ ] Scrub/mask images by default on user sessions
- [ ] Update the [README.md](https://github.com/getsentry/sentry-replay#sentry-replay) to reflect the changes

**Comment by billyvg** [comment]
Note this may take longer as rrweb only supports blocking a single element.
