### ISSUE TITLE
Issue: failed to compile: Cannot find module '@/types'

### ISSUE THREAD

**Issue by BMayhew** [getsentry/sentry-replay#241]
### Environment

NODE: v16.14.2
using npm (not yarn)
Mac OS M1 12.6 Monterey
Angular Project (@sentry/angular 7.11.0) for browser and (@sentry/tracing 7.11.0) for tracing

What version are you running? Etc.
0.6.2

### Steps to Reproduce

followed readme, installing and saving the node @sentry/replay 0.6.2 module

when running `ng serve` and compiling angular we got the below error

```
Error: node_modules/@sentry/replay/dist/types/src/api/captureReplayEvent.d.ts:1:30 - error TS2307: Cannot find module '@/types' or its corresponding type declarations.

1 import { InitialState } from '@/types';

✖ Failed to compile.
```

Appears to be in this line of code - https://github.com/getsentry/sentry-replay/blob/80ca2132f05b9216a9171320076c75f8b9325593/src/api/captureReplayEvent.ts#L4

We were able to resolve this on our local environment but modifying the `../node_modules/@sentry/replay/dist/types/src/api/captureReplayEvent.d.ts` 

Changing from
`import { InitialState } from '@/types';`

Changing to
`import { InitialState } from '../types';`

**Comment by billyvg** [comment]
Thanks @BMayhew, I'll look into this.

**Comment by billyvg** [comment]
@BMayhew `0.6.3` is published to address this, lmk if that fixes it for you

**Comment by BMayhew** [comment]
@billyvg confirmed things work with the latest thanks for the fast turn around!
