### ISSUE TITLE
Improve Session Replay onboarding instructions by adding relevant high-level SDK settings

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-replay#255]
**Problem:**

Users want to associate sessions with usernames rather than user email. It is unclear how to accomplish this from our onboarding instructions today for the `@sentry/replay` SDK.

There are some high-level SDK settings that apply to Session Replay. It should be clear how those interact with the Session Replay product.

**Solution:**

1. Reference high-level SDK settings [such as `Sentry.setUser`](https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/) in onboarding instructions to educate users on other ways to associate a session to an end-user in the Session Replay product. 

2. Reference how to set up custom tags and how these can be used in Session Replay.

**Comment by billyvg** [comment]
@jas-kas should this be in the README or elsewhere?

**Comment by jas-kas** [comment]
@billyvg Yup, in the README!
