### ISSUE TITLE
Explore/document CSP requirements for loading compression webworker

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-replay#265]
We currently require a Content Security Policy of `worker-src blob:` in order to load our Compression webworker. If it fails to load, the SDK will fallback and send uncompressed payloads.

This rule is a bit too relaxed and we may need to load the worker script from the Sentry CDN. We need to be make this doesn't negatively impact the dev experience too much (we probably need to keep loading via blob for development).

**Comment by mydea** [comment]
The worker generally is a topic to touch on again. IMHO it may make sense to extract this out of the SDK and host it somewhere else, would simplify a lot of stuff.
