### ISSUE TITLE
For error-only sessions, keep an additional checkout in buffer

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-replay#273]
For error-only sessions, we checkout the DOM every minute and wait for an error before sending/creating the replay event. This means that if an error happens near immediately after a checkout, we will not much of a replay leading up to the error. We should instead keep an additional checkout in the buffer so that we'll have at a minimum 1 minutes worth (and up to 2 minutes) of replay data.

**Comment by serhanelmali** [comment]
++++++++++++++++
