### ISSUE TITLE
Make Sentry Replay available via CDN packages

### ISSUE THREAD

**Issue by jbm1991** [getsentry/sentry-replay#295]
I would love to Sentry Replay and my company has it enabled for our account. Unfortunately however we have to use the CDN packages to load Sentry, rather than the ways suggested in the README.
Is it possible and/or are there any plans to make this available through the CDN packages?

Thanks
John

**Comment by bruno-garcia** [comment]
Thanks for the feedback John. We're indeed planning on having this SDK available via the CDN in the next weeks. In fact, the plan right now is to merge this code base into the [JS SDK monorepo](https://github.com/getsentry/sentry-javascript) and use the same release automation pipeline which updates the CDN.
 
We'll update this issue accordingly.

**Comment by bruno-garcia** [comment]
The SDK is now available via the CDN: https://docs.sentry.io/platforms/javascript/session-replay/#installation

```html
<script
  src="https://browser.sentry-cdn.com/7.24.1/replay.min.js"
  integrity="sha384-ifYtT/moOdbKa0RUX6esCLi2AU6bNBHWE13ESYZ4Q2j/RFVx1iuIcYadvhEbGMjF"
  crossorigin="anonymous"
></script>
```

This will add the Replay functionality to your Sentry set up (like baritone JS or React/Vue/Angular integration).
Don't forget to align the version of your JS SDK. For example, if you're using `bundle.min.js`, keep both at 7.24.1 or newer feature as you update:

```html
<script
  src="https://browser.sentry-cdn.com/7.24.1/bundle.min.js"
  integrity="sha384-Bol4tOwPZZ8d2kS+v4+iqy1AKEd51Jy/k1G4foXIAMD5+vRmz/0Dh2C2qzIcUs/S"
  crossorigin="anonymous"
></script>
```
