### ISSUE TITLE
Images are missing in the replay video

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-replay#328]
Bug:

A customer has observed that only part of their images are being displayed in the replay video when compared to their actual website.

See this [private Jira ticket for a specific Replay example + customer details](https://getsentry.atlassian.net/browse/FEEDBACK-1671).

**Comment by ryan953** [comment]
I suspect the reason for this problem is that the user was using a slow network. The replay in question shows a mobile device.

I've followed up with the customer and will close this when I hear back.

**Comment by ryan953** [comment]
Closing
