### ISSUE TITLE
Attempt to filter RRWeb Errors from showing up in customer's sentry Issues list

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry-replay#334]
### Problem:
When a user deploys our replay SDK, there is a chance that we can create RRWeb errors. right now these will show up in their sentry issues list, and take up error quota. This is a problem as we shouldn't be consuming quotas with our own SDK.

This also doesn't help us debug these issues unless a customer reports them. Can we figure out a way swallow these errors, and perhaps somehow report them to our internal logging via client reports / some other way?

**Comment by mydea** [comment]
See: https://github.com/getsentry/sentry-javascript/issues/6418
